// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 48hdstfvEZkFZSekMr6Q9R
// Component: zgd6BbwsrQ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: lG_kCkkDwr/component
import Footer from "../../Footer"; // plasmic-import: z3CYKlSW6J/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_robot_draws_you.module.css"; // plasmic-import: 48hdstfvEZkFZSekMr6Q9R/projectcss
import * as sty from "./PlasmicFaceTrace.module.css"; // plasmic-import: zgd6BbwsrQ/css

import GirlsvgIcon from "./icons/PlasmicIcon__Girlsvg"; // plasmic-import: IhX7J1b9U/icon
import LylesvgIcon from "./icons/PlasmicIcon__Lylesvg"; // plasmic-import: jB3ni26Ms/icon
import TresAmigossvgIcon from "./icons/PlasmicIcon__TresAmigossvg"; // plasmic-import: goZ5zsJ1G/icon
import DarrensvgIcon from "./icons/PlasmicIcon__Darrensvg"; // plasmic-import: 5hYWAQeGL/icon

export type PlasmicFaceTrace__VariantMembers = {};

export type PlasmicFaceTrace__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaceTrace__VariantsArgs;
export const PlasmicFaceTrace__VariantProps = new Array<VariantPropType>();

export type PlasmicFaceTrace__ArgsType = {};
type ArgPropType = keyof PlasmicFaceTrace__ArgsType;
export const PlasmicFaceTrace__ArgProps = new Array<ArgPropType>();

export type PlasmicFaceTrace__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultFaceTraceProps {
  dataFetches: PlasmicFaceTrace__Fetches;
}

function PlasmicFaceTrace__RenderFunc(props: {
  variants: PlasmicFaceTrace__VariantsArgs;
  args: PlasmicFaceTrace__ArgsType;
  overrides: PlasmicFaceTrace__OverridesType;
  dataFetches?: PlasmicFaceTrace__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Store - FaceTrace"}</title>
        <meta
          key="og:title"
          property="og:title"
          content={"Store - FaceTrace"}
        />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__gTz4
            )}
          >
            {"FaceTrace"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__n2GQz
            )}
          >
            {
              "Custom artwork created from your photos and drawn with pen plotter machines."
            }
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___2UPnJ
            )}
          >
            {"$100 - $500"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__vCdrn
            )}
          >
            {
              "Price varies based on complexity of photo submitted and amount of detail in the final output."
            }
          </div>

          <div className={classNames(defaultcss.all, sty.box__t49I7)}>
            <div className={classNames(defaultcss.all, sty.box__cSmA)}>
              <GirlsvgIcon
                className={classNames(defaultcss.all, sty.svg__abAfL)}
                role={"img"}
              />

              <LylesvgIcon
                className={classNames(defaultcss.all, sty.svg__fyCw6)}
                role={"img"}
              />

              <TresAmigossvgIcon
                className={classNames(defaultcss.all, sty.svg__pf95X)}
                role={"img"}
              />

              <DarrensvgIcon
                className={classNames(defaultcss.all, sty.svg__xA90W)}
                role={"img"}
              />
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "footer"],
  header: ["header"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaceTrace__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaceTrace__VariantsArgs;
    args?: PlasmicFaceTrace__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFaceTrace__Fetches;
  } & Omit<PlasmicFaceTrace__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFaceTrace__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFaceTrace__ArgProps,
      internalVariantPropNames: PlasmicFaceTrace__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFaceTrace__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaceTrace";
  } else {
    func.displayName = `PlasmicFaceTrace.${nodeName}`;
  }
  return func;
}

export const PlasmicFaceTrace = Object.assign(
  // Top-level PlasmicFaceTrace renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicFaceTrace
    internalVariantProps: PlasmicFaceTrace__VariantProps,
    internalArgProps: PlasmicFaceTrace__ArgProps
  }
);

export default PlasmicFaceTrace;
/* prettier-ignore-end */
