// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 48hdstfvEZkFZSekMr6Q9R
// Component: REE5CL2t6A
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: lG_kCkkDwr/component
import Footer from "../../Footer"; // plasmic-import: z3CYKlSW6J/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_robot_draws_you.module.css"; // plasmic-import: 48hdstfvEZkFZSekMr6Q9R/projectcss
import * as sty from "./PlasmicMaps.module.css"; // plasmic-import: REE5CL2t6A/css

export type PlasmicMaps__VariantMembers = {};

export type PlasmicMaps__VariantsArgs = {};
type VariantPropType = keyof PlasmicMaps__VariantsArgs;
export const PlasmicMaps__VariantProps = new Array<VariantPropType>();

export type PlasmicMaps__ArgsType = {};
type ArgPropType = keyof PlasmicMaps__ArgsType;
export const PlasmicMaps__ArgProps = new Array<ArgPropType>();

export type PlasmicMaps__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultMapsProps {
  dataFetches: PlasmicMaps__Fetches;
}

function PlasmicMaps__RenderFunc(props: {
  variants: PlasmicMaps__VariantsArgs;
  args: PlasmicMaps__ArgsType;
  overrides: PlasmicMaps__OverridesType;
  dataFetches?: PlasmicMaps__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Store - Maps"}</title>
        <meta key="og:title" property="og:title" content={"Store - Maps"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__smsZu
            )}
          >
            {"Maps"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__hcMnt
            )}
          >
            {
              "Custom Maps created from public data sources, massaged until perfect for plotting, and drawn with one of our machines."
            }
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__srtDm
            )}
          >
            {
              "Add your personal touch or enjoy the clean simplicity of our base maps."
            }
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__oEGaj
            )}
          >
            {"$250 - $700"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__xMWqa
            )}
          >
            {
              "Price varies based on map data availability and amount of detail in the final output."
            }
          </div>

          <div className={classNames(defaultcss.all, sty.box__gj2Lw)}>
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__sgZc)}
              role={"img"}
              src={"/plasmic/robot_draws_you/images/keyWest.png"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__wh7Nb)}
              role={"img"}
              src={"/plasmic/robot_draws_you/images/brooklynTopo.png"}
            />
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "footer"],
  header: ["header"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMaps__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMaps__VariantsArgs;
    args?: PlasmicMaps__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMaps__Fetches;
  } & Omit<PlasmicMaps__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMaps__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMaps__ArgProps,
      internalVariantPropNames: PlasmicMaps__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMaps__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMaps";
  } else {
    func.displayName = `PlasmicMaps.${nodeName}`;
  }
  return func;
}

export const PlasmicMaps = Object.assign(
  // Top-level PlasmicMaps renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicMaps
    internalVariantProps: PlasmicMaps__VariantProps,
    internalArgProps: PlasmicMaps__ArgProps
  }
);

export default PlasmicMaps;
/* prettier-ignore-end */
