// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 48hdstfvEZkFZSekMr6Q9R
// Component: bUlzF8Q1_w
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_robot_draws_you.module.css"; // plasmic-import: 48hdstfvEZkFZSekMr6Q9R/projectcss
import * as sty from "./PlasmicHomepageSlideshow.module.css"; // plasmic-import: bUlzF8Q1_w/css

import RTrimsvgIcon from "./icons/PlasmicIcon__RTrimsvg"; // plasmic-import: GzS58aHp0/icon

export type PlasmicHomepageSlideshow__VariantMembers = {};

export type PlasmicHomepageSlideshow__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepageSlideshow__VariantsArgs;
export const PlasmicHomepageSlideshow__VariantProps =
  new Array<VariantPropType>();

export type PlasmicHomepageSlideshow__ArgsType = {};
type ArgPropType = keyof PlasmicHomepageSlideshow__ArgsType;
export const PlasmicHomepageSlideshow__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepageSlideshow__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultHomepageSlideshowProps {
  className?: string;
}

function PlasmicHomepageSlideshow__RenderFunc(props: {
  variants: PlasmicHomepageSlideshow__VariantsArgs;
  args: PlasmicHomepageSlideshow__ArgsType;
  overrides: PlasmicHomepageSlideshow__OverridesType;
  dataFetches?: PlasmicHomepageSlideshow__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <RTrimsvgIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        id={"homepageAnimation" as const}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepageSlideshow__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepageSlideshow__VariantsArgs;
    args?: PlasmicHomepageSlideshow__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepageSlideshow__Fetches;
  } & Omit<PlasmicHomepageSlideshow__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepageSlideshow__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepageSlideshow__ArgProps,
      internalVariantPropNames: PlasmicHomepageSlideshow__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepageSlideshow__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepageSlideshow";
  } else {
    func.displayName = `PlasmicHomepageSlideshow.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepageSlideshow = Object.assign(
  // Top-level PlasmicHomepageSlideshow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicHomepageSlideshow
    internalVariantProps: PlasmicHomepageSlideshow__VariantProps,
    internalArgProps: PlasmicHomepageSlideshow__ArgProps
  }
);

export default PlasmicHomepageSlideshow;
/* prettier-ignore-end */
